# Generated by Django 6.0.5 on 2026-06-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.publisher'),
            preserve_default=False,
        ),
    ]
